DEVICE_NAME = "board1"

WIFI_SSID = ""
WIFI_PASSWORD = ""

BROKER_URL = ""
BROKER_PORT = 1883
BROKER_USERNAME = ""
BROKER_PASSWORD = ""

SCD30_MEASUREMENT_INTERVAL = 5
SCD30_ALTITUDE = 417
SCD30_AMBIENT_PRESSURE = 964
SCD30_TEMPERATURE_OFFSET = 0
