DEVICE_NAME = "board1"

MODULE_SCD30 = 0
MODULE_PM25 = 0
MODULE_PIR = 0
MODULE_DOOR = 0

WIFI_SSID = ""
WIFI_PASSWORD = ""

BROKER_URL = ""
BROKER_PORT = 1883
BROKER_USERNAME = ""
BROKER_PASSWORD = ""

SCD30_MEASUREMENT_INTERVAL = 5
SCD30_ALTITUDE = 417
SCD30_AMBIENT_PRESSURE = 964
SCD30_TEMPERATURE_OFFSET = 0
